[package]
name = "firecore-battle"
description = "Pokemon battle simulation"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
version = "0.0.8"
license = "MIT"
edition = "2018"
repository = "https://github.com/fiirecore/battle"
readme = "README.md"
categories = ["game-development", "game-engines"]
keywords = ["pokemon", "battle", "turn-based"]

[features]
default = ["host", "ai", "default_engine_scripting"]

engine = ["rand"]

host = ["engine", "log"]

default_engine = ["engine", "log"]
default_engine_scripting = ["default_engine", "rhai"]

ai = ["mpsc_endpoint", "rand", "log"]

mpsc_endpoint = ["crossbeam-channel", "log"]

[dependencies]

# firecore-pokedex = "0.0.7"
firecore-pokedex = { git = "https://github.com/fiirecore/pokedex", rev = "18f1de3" }
# firecore-pokedex = { path = "../pokedex" }

serde = { version = "1", features = ["derive"] }

rand = { version = "0.8", default-features = false, optional = true }
log = { version = "0.4", optional = true }

rhai = { git = "https://github.com/DoNotDoughnut/rhai", rev = "b66b919", optional = true }

crossbeam-channel = { version = "0.5", optional = true }

[dev-dependencies]
simple_logger = "1"
