[package]
name = "firecore-battle"
version = "0.5.0-beta.2021-08-22"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[features]
default = ["host", "rhai"]
host = []
ai = []

[dependencies]
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/firecore-pokedex", default-features = false }
rand = { version = "0.8", default-features = false }
log = "0.4"
hashbrown = "0.11" 
serde = { version = "1.0", features = ["derive"] }
rhai = { version = "1", optional = true }