[package]
name = "firecore-battle"
version = "0.5.0-beta.2021-07-27"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[features]
default = []
ai = []

[dependencies]
rand = { version = "0.8", default-features = false }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/firecore-pokedex" }