[package]
name = "firecore-battle"
version = "0.0.2" # "0.5.0-beta.2021-08-22"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"
description = "Pokemon battle simulation"
license = "MIT"
repository = "https://github.com/fiirecore/battle"
readme = "README.md"
categories = ["game-development", "game-engines"]
keywords = ["pokemon", "battle", "turn-based"]

[features]
default = ["host", "scripting", "ai"]
scripting = ["rhai"]
host = []
ai = []

[dependencies]
firecore-pokedex = "0.0.4"
rand = { version = "0.8", default-features = false }
log = "0.4"
hashbrown = "0.11"
serde = { version = "1", features = ["derive"] }
serde-big-array = { version = "0.3", features = ["const-generics"] }
rhai = { version = "1", optional = true }