[package]
name = "firecore-battle"
description = "Pokemon battle simulation"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
version = "0.0.6"
license = "MIT"
edition = "2018"
repository = "https://github.com/fiirecore/battle"
readme = "README.md"
categories = ["game-development", "game-engines"]
keywords = ["pokemon", "battle", "turn-based"]

[features]
default = ["host", "ai", "default_engine_scripting"]

engine = []

host = ["engine"]

default_engine = ["engine"]
default_engine_scripting = ["default_engine", "rhai"]

ai = ["mpsc_endpoint"]

mpsc_endpoint = ["crossbeam-channel"]

[dependencies]
firecore-pokedex = "0.0.6"
rand = { version = "0.8", default-features = false }
log = "0.4"
hashbrown = "0.11"
serde = { version = "1", features = ["derive"] }
serde-big-array = { version = "0.3", features = ["const-generics"] }
rhai = { version = "1", optional = true }
crossbeam-channel = { version = "0.5", optional = true }

[dev-dependencies]
simple_logger = "1"
rand = "0.8"