[package]
name = "firecore-battle"
description = "Pokemon battle simulation"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
version = "0.0.9"
license = "CC0-1.0"
edition = "2021"
repository = "https://github.com/fiirecore/battle"
readme = "README.md"
categories = ["game-development", "game-engines"]
keywords = ["pokemon", "battle", "turn-based"]

[features]
default = ["host", "ai", "default_engine_scripting"]

move_engine = ["rand"]
item_engine = ["move_engine"]

host = ["move_engine", "item_engine", "log"]

default_engine = ["move_engine", "item_engine", "log"]
default_engine_scripting = ["default_engine", "rhai"]


ai = ["mpsc_endpoint", "rand", "log"]

mpsc_endpoint = ["crossbeam-channel", "log"]

[dependencies]

firecore-pokedex = { version = "0.0.8", git = "https://github.com/fiirecore/pokedex", rev = "4dc9632" }
# firecore-pokedex = { path = "../pokedex" }

serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", default-features = false, optional = true }
log = { version = "0.4", optional = true }
hashbrown = { version = "0.12", features = ["serde"] }
enum-map = "2"

rhai = { version = "1.7", optional = true }

crossbeam-channel = { version = "0.5", optional = true }

[dev-dependencies]
simple_logger = "2"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }

[workspace]
default-members = ["crates/*"]
members = ["crates/*"]